[build]
builder = "nixpacks"
buildCommand = "cd backend && npx prisma generate"

[deploy]
startCommand = "cd backend && node src/index.js"
preDeployCommand = "cd backend && DATABASE_URL=$DB_DIRECT_URL npx prisma db push"
healthcheckPath = "/api/health"
healthcheckTimeout = 30
