[build]
builder = "nixpacks"
buildCommand = "npx prisma generate"

[deploy]
startCommand = "node src/index.js"
preDeployCommand = "DATABASE_URL=$DIRECT_URL npx prisma db push"
healthcheckPath = "/api/health"
healthcheckTimeout = 30
