[build]
builder = "nixpacks"
buildCommand = "npx prisma generate"

[deploy]
startCommand = "node src/index.js"
releaseCommand = "npx prisma db push"
healthcheckPath = "/api/health"
healthcheckTimeout = 30
